// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for urn://x-artefacts-gnivc-ru/ais3/kkt/AuthService/types/1.0
package tns

import (
	"encoding/xml"
)

// Element
type AuthServiceFault struct {
	XMLName xml.Name `xml:"AuthServiceFault"`

	Message string `xml:",any"`
}

// Element
type AuthRequest struct {
	XMLName     xml.Name    `xml:"urn://x-artefacts-gnivc-ru/ais3/kkt/AuthService/types/1.0 AuthRequest"`
	AuthAppInfo AuthAppInfo `xml:",any"`
}

// Element
type AuthResponse struct {
	XMLName xml.Name `xml:"AuthResponse"`

	Result *AuthResponseResult `xml:"Result"`

	Fault *AuthServiceFault `xml:"AuthServiceFault"`
}

// Element
type AuthResponseResult struct {
	XMLName xml.Name `xml:"Result"`

	Token string `xml:"Token"`

	ExpireTime string `xml:"ExpireTime"`
}

// XSD ComplexType declarations

type AuthAppInfo struct {
	XMLName xml.Name

	MasterToken string `xml:",any"`

	InnerXml string `xml:",innerxml"`
}
